spring.application.name=ApiGatewayApplication
server.port=8070


eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=RetailFlowSecretKeyRetailFlowSecretKeyRetailFlow2026


spring.cloud.gateway.routes[0].id=Auth
spring.cloud.gateway.routes[0].uri=http://localhost:8071
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=UserApplication
spring.cloud.gateway.routes[1].uri=http://localhost:8072
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[2].id=AuditLogApplication
spring.cloud.gateway.routes[2].uri=http://localhost:8073
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/audit-logs/**

spring.cloud.gateway.routes[3].id=Notification
spring.cloud.gateway.routes[3].uri=http://localhost:8074
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/notifications/**



# Sale service
spring.cloud.gateway.routes[4].id=SaleService
spring.cloud.gateway.routes[4].uri=http://localhost:8079
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/sales/**

# Invoice service
spring.cloud.gateway.routes[5].id=InvoiceService
spring.cloud.gateway.routes[5].uri=http://localhost:8084
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/invoices/**

# Payment service
spring.cloud.gateway.routes[6].id=PaymentService
spring.cloud.gateway.routes[6].uri=http://localhost:8081
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/payments/**

# ? Product Service
spring.cloud.gateway.routes[7].id=product
spring.cloud.gateway.routes[7].uri=http://localhost:8077
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/products/**

# ? Catalog Service
spring.cloud.gateway.routes[8].id=catalog
spring.cloud.gateway.routes[8].uri=http://localhost:8078
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/catalogs/**


spring.cloud.gateway.routes[9].id=Inventory
spring.cloud.gateway.routes[9].uri=http://localhost:8075
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/inventory/**

spring.cloud.gateway.routes[10].id=PurchaseOrder
spring.cloud.gateway.routes[10].uri=http://localhost:8076
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/purchase-orders/**

spring.cloud.gateway.routes[11].id=KpiReport
spring.cloud.gateway.routes[11].uri=http://localhost:8082
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/kpi-reports/**

spring.cloud.gateway.routes[12].id=ComplianceReport
spring.cloud.gateway.routes[12].uri=http://localhost:8085
spring.cloud.gateway.routes[12].predicates[0]=Path=/api/compliance-reports/**

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true